### ISSUE TITLE
issue from ploting of phase or need to minimize the phase gradient within the scan region

### ISSUE THREAD

**Issue by XLIU-1993** [PtyLab/PtyLab.py#34]
I used mPIE to reconstruct my simulated obj= amp*exp(1j*phase); obj amplitude and phase are shown on the right side figure, and the probe has a constant phase value. 

Firstly, I wonder if the reconstruction worked properly because applying np.angle(object) does not resolve the phase. Is it related to the minimization of the phase gradient which caused the phase jump? Function in BaseEngine _setObjectProbeROI seems not to calculate a polygon ROI. Can I use this ROI as a mask to write a minimization of phase gradient?

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/5970687/226485389-4ac914bb-a178-456c-b5f4-cfc3aaef1c92.png">

Secondly, the obj amplitude is obtained by doing abs(object), it seems like the reconstructed obj amplitude has some 'footprints' of the obj phase; check the 'wrinkles' on the left side obj amplitude image. It feels like the abs(object) = abs(abs(fft(obj amplitude))+np.angle(fft(obj phase))). I don't really understand how it looks like this, could you give some insights please?

<img width="958" alt="image" src="https://user-images.githubusercontent.com/5970687/226486542-b42422b3-c74a-476a-9e88-2a45714d188c.png">

**Comment by dboonz** [comment]
Hi Xliu,

Could you give us a bit more specifics about your simulation? It looks a bit like your algorithm didn't converge. How many iterations did you run?  What is the size of your scan grid? Do you have a simulation script that you're willing to share? In other words, could you give us a reproducible example?

My first estimate would be that you may not have enough diffraction patterns, or that you need to run more iterations.

kind regards,
Dirk

**Comment by XLIU-1993** [comment]
Dear Dirk,

Thank you for the response! Firstly, for your questions, the cam_pxlnb is (256,256), the probe is a Gaussian distribution with sigma=32 pixels, and the scan pattern is generated using Archimedes spiral function with a scan_step = 38 pixels. 100 scan steps were used.  And the iteration number of mPIE is 300.

I found out that the 'phase jump' was caused by the 'params.backgroundModeSwitch = True', the phase is well resolved as long as this parameter is switched back to False. I did reconstruction with the same dataset by only switching this parameter on and off, results are shown below. Do you know how could this parameter influence the reconstruction?

At last, you may notice that the probe is not centered on the matrix, is this normal?

Best regards,
Xu

<img width="490" alt="image" src="https://user-images.githubusercontent.com/5970687/226941340-c9818eff-e8cf-4b44-a471-22a6a9fd2831.png">

**Comment by roflmaostc** [comment]
Try to set [this](https://github.com/PtyLab/PtyLab.py/blob/3b71548d6369919e9d428287554f72c58f5f9b19/PtyLab/Params/Params.py#L83) to true, such that the probe is move to the center after each iteration through the ptychogram.

**Comment by XLIU-1993** [comment]
It works fine with rofmaostc's suggestion! I read your arvix preprint on Ptylab and the wavefront measuring technique with Ptychography, very impressing work guys! I close this issue, but I think you might need to check the estimation of the background in the future, have a good day!

![image](https://user-images.githubusercontent.com/5970687/226944621-09117918-a051-4807-bad1-3f8a0be07baf.png)

**Comment by XLIU-1993** [comment]
The sampling ratio is well satisfied if your recommendation concerns this. I was using the Fraunhofer propagator. 
And I checked again by plotting the amplitude and phase separately, there are still some phase wrapping , check the red arrow part. Does it connect to the minimization of the phase gradient? Or is this already implemented in PtyLab? 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5970687/226961848-6c077844-a291-4136-a99e-2d8b1d70d6d5.png">

**Comment by roflmaostc** [comment]
Ah I see, your previous image was cropped :smile: 

The raw data looks good in terms of sampling of the probe shape. My concerns were that your previous FoV was too small to capture the probe sufficiently.

**Comment by dboonz** [comment]
Hi Xliu,

The overall phase of the reconstruction is not normalized, so that could be any arbitrary number. You can try to use something like this: https://scikit-image.org/docs/stable/auto_examples/filters/plot_phase_unwrap.html to unwrap the phase, or set a single pixel to a known value for your simulation.
