### ISSUE TITLE
scipy version conflict when using setup.py to install dependencies

### ISSUE THREAD

**Issue by DanielKaschubek-yuri** [PtyLab/PtyLab.py#36]
When using the setup.py file with the stated run command for setup.py from the readme in spyder (version 5.4.2) it results in an error due to conflicting scipy version requirements:

```
DistutilsError: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8 is required by {'scikit-image'}

During handling of the above exception, another exception occurred:

SystemExit: error: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8 is required by {'scikit-image'}
```

The used virtual environment was newly created in anaconda and only the spyder Kernels 2.4.0 were installed before running the setup file. See also the attached output of conda list for the used environment before running setup.py
[CondaListEnvironment before setup.txt](https://github.com/PtyLab/PtyLab.py/files/11079799/CondaListEnvironment.before.setup.txt)

**Comment by roflmaostc** [comment]
Hi,

I can reproduce with Python 3.9.16:
```
Adding networkx 3.0 to easy-install.pth file

Installed /home/felix/anaconda3/envs/ptylab/lib/python3.9/site-packages/networkx-3.0-py3.9.egg
error: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8 is required by {'scikit-image'}
```

@dboonz can you fix that?

**Comment by roflmaostc** [comment]
@dboonz @MaisieD still failing I believe.
Can you please look into that?
Would be unfortunate if the paper is published and the installation fails :laughing:

**Comment by MaisieD** [comment]
Hello, 
I checked the runtime requirements for scikit-image:
scipy>=1.8,<1.9.2; python_version<='3.9'
scipy>=1.8; python_version>'3.9'
So, I guess you need to upgrade python? Or downgrade scipy?

**Comment by roflmaostc** [comment]
should we downgrade scipy in that case?

Or is it possible to specify the versions more precisely for different python version?

I guess, at the moment people are using Python 3.8, 3.9 and 3.10. So PtyLab.py should run on all version.

Btw: paper is out today

**Comment by DanielKaschubek-yuri** [comment]
Hello,
the python version I used is also 3.9.16 (see also conda list .txt file). 
The setup indeed works if I use an environment with python 3.11.2. I would suggest adding the python requirement to the readme to make it more obvious that ptylab expects a more recent python version than 3.9

**Comment by DanielKaschubek-yuri** [comment]
While we are at the dependencies, after solving the current issue I also noticed the following:
- readHdf5.py imports tables, but pytables is outcommented as a dependency in the setup. Therefore I had to manually install it
- visualisation.py has a catch for the import of pyqtgraph but pg is still used in the function "show3Dslider" in line 263 and 264. The simulateData.py file calls this function in line 204 and therefore cannot be run without installing pyqtgraph manually. I would suggest to add a catch to the show3DSlider function to check whether pyqtgraph is installed and if not, throw a warning but do not create the plot

**Comment by dboonz** [comment]
Oh, thanks for pointing that out! It should be fairly easy to get rid of the tables dependency, and let's make an issue for the second point.

On April 12, 2023 1:23:12 PM GMT+02:00, DanielKaschubek-yuri ***@***.***> wrote:
>While we are at the dependencies, after solving the current issue I also noticed the following:
>- readHdf5.py imports tables, but pytables is outcommented as a dependency in the setup. Therefore I had to manually install it
>- visualisation.py has a catch for the import of pyqtgraph but pg is still used in the function "show3Dslider" in line 263 and 264. The simulateData.py file calls this function in line 204 and therefore cannot be run without installing pyqtgraph manually. I would suggest to add a catch to the show3DSlider function to check whether pyqtgraph is installed and if not, throw a warning but do not create the plot
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PtyLab/PtyLab.py/issues/36#issuecomment-1505101993
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dboonz** [comment]
Hi there, closing this as we just moved the package management to Poetry. The scipy version conflict should have been solved.
