### ISSUE TITLE
Bug in Operators.py for scaledPolychromeASP propagator

### ISSUE THREAD

**Issue by apelekan** [PtyLab/PtyLab.py#47]
Line 402 should be: reconstruction.dxd
Line 407 should be: return reconstruction.esw, ifft2c(fft2c(fields) * Q2) * Q1

**Comment by dboonz** [comment]
@larsloetgering  is this correct?

**Comment by apelekan** [comment]
for the current version of the Operators.py in the main branch, it should be lines 407 and 412 I think

**Comment by dannielsantiago** [comment]
This issue is now solved in the main branch
