### ISSUE TITLE
feature: Automatically detecting the GPU and setting `Params.gpuSwitch` to True

### ISSUE THREAD

**Issue by ShantanuKodgirwar** [PtyLab/PtyLab.py#59]
I think a feature to detect automatically an nvidia gpu and set the `Params.gpuSwitch=True` instead of manually setting this could be useful.

**Comment by roflmaostc** [comment]
Does cupy have something like `is_functional`? Just detecting GPU is not enough I believe.

**Comment by ShantanuKodgirwar** [comment]
I haven't really used `cupy`, but there seems to be something [similar](https://docs.cupy.dev/en/stable/user_guide/basic.html#current-device).

**Comment by ShantanuKodgirwar** [comment]
Currently it raises `cupy not available` warning many times when you simply import `ptylab` on CPU. It's a bit cumbersome and unnecessary in my opinion and the package should automatically detect the device and ignore the cupy dependency if it's on CPU.

**Comment by ShantanuKodgirwar** [comment]
However, TensorFlow is a compulsory dependency at the moment, we could do something like

```python
physical_devices = tf.config.list_physical_devices('GPU')
if len(physical_devices) > 0:
    params.gpuSwitch = True
```
However, we need to make sure that this is accessible to all the instances of `params.gpuSwitch`. This feature would mostly be a minor release then.
